services:
  workspace:
   # For the workspace service, we will also create a custom image to install and setup all the necessary stuff.
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    tty: true  # Enables an interactive terminal
    stdin_open: true  # Keeps standard input open for 'docker exec'
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - uhy-network
      
networks:
  uhy-network: